//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTestWPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Stocks
    {
        public int StockId { get; set; }
        public string StockSymbol { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Change { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
